// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWaN2gvhvrDdKOsd4Gjvr9ve6_6lG-NI',
    appId: '1:563873780602:web:561a2a7cbfbe051e96fcc3',
    messagingSenderId: '563873780602',
    projectId: 'nahra-316ee',
    authDomain: 'nahra-316ee.firebaseapp.com',
    storageBucket: 'nahra-316ee.firebasestorage.app',
    measurementId: 'G-TZ8NHY9EWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmyeVEm8IQmTzz8vhYyXYmI6LyGR5Du_w',
    appId: '1:563873780602:android:5138ad021a5afff696fcc3',
    messagingSenderId: '563873780602',
    projectId: 'nahra-316ee',
    storageBucket: 'nahra-316ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpDXWqJQE8-NenV1HaWGdCa80UJylRK4',
    appId: '1:563873780602:ios:79467d8757ab5b0f96fcc3',
    messagingSenderId: '563873780602',
    projectId: 'nahra-316ee',
    storageBucket: 'nahra-316ee.firebasestorage.app',
    iosBundleId: 'com.example.nashraProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEpDXWqJQE8-NenV1HaWGdCa80UJylRK4',
    appId: '1:563873780602:ios:79467d8757ab5b0f96fcc3',
    messagingSenderId: '563873780602',
    projectId: 'nahra-316ee',
    storageBucket: 'nahra-316ee.firebasestorage.app',
    iosBundleId: 'com.example.nashraProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCWaN2gvhvrDdKOsd4Gjvr9ve6_6lG-NI',
    appId: '1:563873780602:web:17038403a42bc25c96fcc3',
    messagingSenderId: '563873780602',
    projectId: 'nahra-316ee',
    authDomain: 'nahra-316ee.firebaseapp.com',
    storageBucket: 'nahra-316ee.firebasestorage.app',
    measurementId: 'G-WLE1Z3Y8HS',
  );
}
