import 'package:flutter/material.dart';
import 'package:nashra_project2/models/announcement.dart';
import 'package:nashra_project2/providers/announcementsProvider.dart';
import 'package:nashra_project2/providers/authProvider.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';

class Buttomsheetannouncement extends StatefulWidget {
  @override
  State<Buttomsheetannouncement> createState() => ButtomsheetannouncementState();
}

class ButtomsheetannouncementState extends State<Buttomsheetannouncement> {
  final titleController = TextEditingController();
  final descriptionController = TextEditingController();
  final fileUrlController = TextEditingController();

  File? _imageFile;

  final ImagePicker _imagePicker = ImagePicker();

  Future<void> _pickImage() async {
    final pickedFile = await _imagePicker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  Future<void> postAnnouncement() async {
    final announcementsProvider =
        Provider.of<Announcementsprovider>(context, listen: false);
    final auth = Provider.of<AuthProvider>(context, listen: false);

    try {
      final newAnnouncement = Announcement(
        id: '', // Will be generated by Firebase
        title: titleController.text,
        description: descriptionController.text,
        likes: 0,
        likedByUser: [],
        createdAt: DateTime.now(),
        imageUrl: _imageFile != null ? _imageFile!.path : null,
        fileUrl: fileUrlController.text.trim().isEmpty ? null : fileUrlController.text.trim(),
        commentsNo: 0,
      );

      await announcementsProvider.addAnnouncement(newAnnouncement, auth.token);

      Navigator.pop(context); // Close the bottom sheet
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to post announcement: ${e.toString()}')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Color(0xFFFEFFF3),
        borderRadius: BorderRadius.circular(12.0),
      ),
      padding: const EdgeInsets.all(16),
      child: ListView(
        shrinkWrap: true,
        children: [
          const Text(
            'Add Announcement',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.black,
            ),
          ),
          SizedBox(height: 10),
          TextField(
            controller: titleController,
            decoration: InputDecoration(
              hintText: 'Announcement title',
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(5)),
              contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
            ),
          ),
          SizedBox(height: 10),
          TextField(
            controller: descriptionController,
            decoration: InputDecoration(
              hintText: 'Announcement description',
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(5)),
              contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
            ),
          ),
          SizedBox(height: 10),
          TextField(
            controller: fileUrlController,
            decoration: InputDecoration(
              hintText: 'Paste file URL (e.g. Google Drive)',
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(5)),
              contentPadding: const EdgeInsets.symmetric(vertical: 10, horizontal: 16),
            ),
          ),
          SizedBox(height: 10),
          Text('Add Image:'),
          GestureDetector(
            onTap: _pickImage,
            child: Container(
              height: 120,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.green),
                borderRadius: BorderRadius.circular(8),
                color: Colors.grey[200],
              ),
              child: Center(
                child: _imageFile == null
                    ? Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.image, color: Colors.grey),
                          Text("Select image"),
                        ],
                      )
                    : Image.file(_imageFile!, fit: BoxFit.cover),
              ),
            ),
          ),
          SizedBox(height: 10),
          TextButton(
            onPressed: postAnnouncement,
            child: Text(
              'Post',
              style: TextStyle(color: Colors.white),
            ),
            style: TextButton.styleFrom(
              backgroundColor: Colors.green,
            ),
          )
        ],
      ),
    );
  }
}
